blog/urls.py
from django.urls import path
from blog.views import home, post_detay

urlpatterns = [
    path('', home, name='blog_list'),
    path('<post_link>/', post_detay, name='blog_detay'),
    
    # path('about/', views.about, name="about"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from config.views import home, isim_yaz, python, ad_soyad_yaz


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    
    path('', home, name='home'),
    # path('python/', python),
    # path('<isim>/', isim_yaz),  #bana bir değişken gönderirsen isim_yaz fonksiyonuna gönder demek. Üstteki pythonı alta yazdığımızda ekranda python yazar. 
    # path('<ad>/<soyad>/', ad_soyad_yaz),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, 
                            document_root=settings.MEDIA_ROOT)   

blog/models.py
from django.db import models


class Post(models.Model):
    yayinla = models.BooleanField(default=False)
    baslik= models.CharField(max_length=200, unique = True)
    link = models.SlugField(max_length=200, unique=True)  #SlugField = link
    resim = models.ImageField(upload_to='blog_resim/')
    icerik = models.TextField()
    olusturma = models.DateTimeField(auto_now_add=True)
    guncelleme = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "Baslik : " + self.baslik

# a= None  -> null
# a=''     -> blank

wallet/models.py
from django.db import models
from django.contrib.auth.models import User

class Cuzdan(models.Model):

    class PARA_BIRIMLERI(models.TextChoices):
        USD = 'USD', 'Dolar' 
        EUR = 'EUR', 'Euro'
        TL = 'TL', 'Turk Lirası'
        BTC = 'BTC', 'Bitcoin'


    user = models.ForeignKey(User, on_delete=models.CASCADE) #cascade = kullanıcı silinirse ona bağlı olan tüm cüzdanlarda silinsin.
    para_birimi = models.CharField(max_length=3, choices=PARA_BIRIMLERI.choices, default=PARA_BIRIMLERI.TL)
    bakiye = models.DecimalField(max_digits=6, decimal_places=2)

    class Meta:
        unique_together = ('user', 'para_birimi',)

    def __str__(self):
        return self.user.first_name +' : ' + str(self.bakiye) + self.para_birimi

    

blog/views.py
from django.shortcuts import render, get_object_or_404
from blog.models import Post

def home(request):

    # postlar = Post.objects.all()

    yayinlanmis_postlar = Post.objects.filter(yayinla=True)


    context = {
        'postlar' : yayinlanmis_postlar
    }
    return render(request, 'blog_list.html', context)

def post_detay(request, post_link):
    # post = Post.objects.get(link =post_baslik, yayinla=True)

    post = get_object_or_404(Post, link=post_link, yayinla=True)

    context = {
        'post' : post
    }
    return render(request, 'blog_detay.html', context)

# def post(request, post):
#     post_detay = Post.object.get()

config/views.py
from django.http import HttpResponse
from django.shortcuts import render
# from wallet.models import Cuzdan

def home(request):
    
    context = {}

    if request.user.is_authenticated:
        context['cuzdanlar'] = request.user.cuzdanlar.all()

    # cuzdanlar = Cuzdan.objects.filter(user = request.user)
    # print(dir(request))    

    return render(request, "index.html", context)

def isim_yaz(request,isim):
    return render(request, "isim.html", {'isim': isim})

def python(request):
    return HttpResponse('Bunu göremezsin')

def ad_soyad_yaz(request, ad, soyad):
    return render(request, "adSoyad.html", {'ad': ad, 'soyad':soyad})

wallet/views.py
from django.shortcuts import render

# Create your views here.

templates/adSoyad.html
<div style="text-align: center;">
    <h1> {{ ad }}</h1>
    <h2>{{ soyad }}</h2>
</div>

templates/base.html
{% block header %}
{% include 'menu.html' %}
{% endblock %}

{% block content %}
{% endblock %}

{% block footer %}
<h1 style="text-align: center;">Tüm hakları saklıdır. C {% now 'Y' %} </h1>
{% endblock %}

templates/blog_detay.html
<!-- {% extends 'base.html'%}

{% block content %} -->
<center>
<h1> {{ post.baslik}} </h1>
<a href=" {% url 'blog_list' %} ">Geri</a>
<img src=" {{ post.resim.url }} " alt="" width="200" height="200">
<h2> {{ post.icerik }} </h2>
</center>

<!-- {% endblock %} -->

templates/blog_list.html
{% extends 'base.html'%}

{% block content %}
{% load humanize %}
<center style="margin-top: 40px;">

        <h1> OYK PYTHON 2022 Blog</h1>
        <br><br><br><br>
        <h2 style="text-decoration: underline; margin-bottom: 4%;" >Blog Listesi</h2>

        {% for post in postlar %}

        <h3>{{ post.baslik}}</h3>
        <p>Olusturma: {{ post.olusturma|naturaltime }}, Guncelleme: {{ post.guncelleme}} </p>
        <h2> <a href=" {% url 'blog_detay' post.link %} "> {{ post.baslik }} </a> </h2>
        <img style="width: 200px; height: 200px;" src=" {{post.resim.url}} " alt=" {{ post.baslik}} ">
        <p>{{ post.icerik|truncatechars:80 }}</p>
        <a href="  {% url 'blog_detay' post.link %} ">Detay</a>

        <p style="margin-bottom: 6%;"> Lorem ipsum dolor sit, amet consectetur adipisicing elit. Maiores vel assumenda repudiandae sint ipsa, adipisci blanditiis recusandae autem veniam cupiditate similique perspiciatis repellat itaque, accusamus necessitatibus voluptates tempora mollitia dolores!</p>
{% endfor %}

</center>

{% endblock %}

templates/index.html
{% extends 'base.html'%}

{% block content %}


<br><br><br>

{% if request.user.is_authenticated %}

Hoşgeldin {{request.user.get_full_name}}
<h3>Bakiyeniz : {{bakiye}}</h3>

{% else %}

Bakiyeyi görmek için giriş yapınız

{% endif %}


<!-- {% include 'menu.html' %} -->
<h1>Home</h1>
<h2>Simdiki zaman</h2>

{% for cuzdan in cuzdanlar %}
        <h1>Cuzdanlariniz</h1>
        <h3> <b>User name :</b>  {{ cuzdan.user}}</h3>
        <h3> <b>Para Birimi :</b>  {{ cuzdan.get_para_birimi_display }}</h3>
        <h3> <b>Bakiyeniz :</b>  {{ cuzdan.bakiye }}</h3>

        <p style="margin-bottom: 6%;"> Lorem ipsum dolor sit, amet consectetur adipisicing elit. Maiores vel assumenda repudiandae sint ipsa, adipisci blanditiis recusandae autem veniam cupiditate similique perspiciatis repellat itaque, accusamus necessitatibus voluptates tempora mollitia dolores!</p>
{% endfor %}

{% now "H:i" %}
<p>{% lorem %}</p> 

{% endblock %}

templates/isim.html
<!-- <h1 style="background-color: rgba(100, 211, 242, 0.896); margin:80px; text-align: center;">{{ isim }}</h1>  -->
{{isim}}

templates/menu.html
{% load static %}
<style>
ul {
  list-style-type: none;
  margin: 0;
  padding: 0;
  overflow: hidden;
  background-color: #333333;
}

li {
  float: left;
}

li a {
  display: block;
  color: white;
  text-align: center;
  padding: 16px;
  text-decoration: none;
}

li a:hover {
  background-color: #111111;
}
</style>
<ul>
    <li><img src="{% static 'logo.png' %}" width="50" height="50" alt="My image"></li>
    <li><a href="{% url 'home' %}">Home</a></li>
    <li><a href="{% url 'blog_list' %}">Blog</a></li>
</ul>